services:
  postgres:
    image: postgres:12.20-bullseye
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.11.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - backend
      - microservices
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.9.7-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
      - microservices
    restart: unless-stopped

  service-registry:
    image: numan947/servicereg
    container_name: servicereg
    ports:
      - "8761:8761"
    depends_on:
      - rabbitmq
      - postgres
      - zipkin
      - pgadmin
    networks:
      - backend
      - microservices
    restart: unless-stopped

  config-server:
    image: numan947/configserver
    container_name: config-server
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
    networks:
      - backend
      - microservices
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    restart: unless-stopped

  companyms:
    image: numan947/companyms
    container_name: company-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
    networks:
      - backend
      - microservices
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker


  jobms:
    image: numan947/jobms
    container_name: job-service
    depends_on:
      - config-server
    ports:
      - "8082:8082"
    networks:
      - backend
      - microservices
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  reviewms:
    image: numan947/reviewms
    container_name: review-service
    ports:
      - "8083:8083"
    depends_on:
      - config-server
    networks:
      - backend
      - microservices
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    image: numan947/gatewayms
    container_name: gateway
    depends_on:
      - config-server
    ports:
      - "8084:8084"
    networks:
      - backend
      - microservices
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  backend:
    external: true
  microservices:
    external: true

volumes:
  postgres:
  pgadmin:
